import numpy.typing as npt
import scanpy


def gateThomsonCells(X) -> npt.ArrayLike:
    """Manually gates cell types for Thomson UMAP"""
    scanpy.pp.neighbors(X, n_neighbors=15, use_rep="embedding", random_state=0)
    scanpy.tl.leiden(X, resolution=3, random_state=0)
    X.obs["Cell Type"] = X.obs.leiden.replace(thomson_layer1)
    X.obs["Cell Type2"] = X.obs.leiden.replace(thomson_layer2)

    return X


thomson_layer1 = {"0": "NK Cells",
                       "1": "T Cells",
                       "2": "Monocytes",
                       "3": "Monocytes",
                       "4": "Monocytes",
                       "5": "Monocytes",
                       "6": "Monocytes",
                       "7": "Monocytes",
                       "8": "Monocytes",
                       "9": "Monocytes",
                       "10": "Monocytes",
                       "11": "Monocytes",
                       "12": "Monocytes",
                       "13": "Monocytes",
                       "14": "Monocytes",
                       "15": "Monocytes",
                       "16": "Monocytes",
                       "17": "Monocytes",
                       "18": "Monocytes",
                       "19": "Monocytes",
                       "20": "Monocytes",
                       "21": "Monocytes",
                       "22": "Monocytes",
                       "23": "Monocytes",
                       "24": "Monocytes",
                       "25": "DCs",
                       "26": "Monocytes",
                       "27": "B Cells",
                       "28": "Monocytes",
                       "29": "Monocytes",
                       "30": "Monocytes",
                       "31": "Monocytes",
                       "32": "Monocytes",
                       "33": "T Helpers",
                       "34": "Monocytes",
                       "35": "DCs",
                       "36": "Monocytes",
                       "37": "Monocytes",
                       "38": "Monocytes",
                       "39": "T Cells",
                       "40": "Monocytes",
                       "41": "Monocytes",
                       "42": "Monocytes",
                       "43": "B Cells",
                       "44": "Monocytes"}


thomson_layer2 = {"0": "NK Cells",
                       "1": "Memory T Cells",
                       "2": "Monocytes",
                       "3": "Myeloid Suppressors",
                       "4": "Macrophages",
                       "5": "Monocytes",
                       "6": "Monocytes",
                       "7": "Monocytes",
                       "8": "Macrophages",
                       "9": "Monocytes",
                       "10": "Monocytes",
                       "11": "Monocytes",
                       "12": "Macrophages",
                       "13": "Monocytes",
                       "14": "Monocytes",
                       "15": "Macrophages",
                       "16": "Monocytes",
                       "17": "Monocytes",
                       "18": "Monocytes",
                       "19": "Monocytes",
                       "20": "Monocytes",
                       "21": "Macrophages",
                       "22": "Macrophages",
                       "23": "Monocytes",
                       "24": "Macrophages",
                       "25": "pDCs",
                       "26": "Macrophages",
                       "27": "Memory B",
                       "28": "Fibroblasts",
                       "29": "Activated Monocyte",
                       "30": "Monocytes",
                       "31": "Fibroblasts",
                       "32": "Monocytes",
                       "33": "Cytotoxic T",
                       "34": "Myeloid Suppressors",
                       "35": "cDCs",
                       "36": "Monocytes",
                       "37": "Monocytes",
                       "38": "Monocytes",
                       "39": "CD4 T Cells",
                       "40": "Activated Monocyte",
                       "41": "None",
                       "42": "Macrophages",
                       "43": "Naive B",
                       "44": "Monocytes"}
